import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Header from "./(uiComponents)/Header";

const inter = Inter({ subsets: ["latin"] });
const blanch = localFont({
  src: [
    {
      path: "../public/fonts/BLANCH_CAPS.otf",
      weight: "400",
    },
    {
      path: "../public/fonts/BLANCH_CONDENSED_INLINE.otf",
      weight: "700",
    },
  ],
  variable: "--font-blanch",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${blanch.variable}`}>

        {children}
      </body>
    </html>
  );
}
